appName: servicename
appImage: gcr.io/google-samples/microservices-demo/servicename
appVersion: v.0.0.0
appReplicas: 1
containerPort: 8080
containerEnvVars:
  - name: ENV_TEST
    value: "PASS"

servicePort: 8080
serviceType: ClusterIP
