appName: redis
appImage: redis
appVersion: alpine
appReplicas: 1
containerPort: 6379
volumeName: redis-data
volumeMountPath: /data
containerEnvVars:
  - name: PORT
    value: "6379"

servicePort: 6379
